FROM node:22-slim AS builder

RUN npm install -g pnpm@8.15.6

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/package.json

RUN pnpm install --filter web... --frozen-lockfile

COPY apps/web ./apps/web

RUN pnpm --filter web build

FROM node:22-slim AS runner

WORKDIR /app
ENV NODE_ENV=production


COPY --from=builder /app/apps/web/.output ./.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
